project.name=lab3WEB
project.version=1.0-SNAPSHOT
project.groupId=se.ifmo
project.packaging=war

java.source.version=17
java.target.version=17
project.encoding=UTF-8

app.context.root=/

db.datasource=java:/PostgresDS
db.dialect=org.hibernate.dialect.PostgreSQLDialect
db.schema.action=update

test.report.dir=target/surefire-reports
